### ISSUE TITLE
about the entropy diagram in Fig.2

### ISSUE THREAD

**Issue by amiltonwong** [happenwah/FVI_CV#1]
Hi, @happenwah ,

Thanks for releasing the package. I'm interested in how to make the `entropy diagram` in [Fig.2](https://www.dropbox.com/s/nkfno0jiugxxm2m/Fig2.jpg?dl=0) in your paper. Could you release the corresponding code? Or could you list the main steps or hints on how to make the `entropy diagram`?

THX!

**Comment by happenwah** [comment]
Hi @amiltonwong, thank you for your interest in our repository!

Code to compute plots as in Figure 2 can be found in the function `plot_per_image` from file `lib/utils/fvi_seg_utils.py`, where the 4th column corresponds to the predictive entropy.
